title: FLASH on TSCC Tutorial
description: Step-by-step guide for building and running FLASH 4.7.1 on SDSC TSCC
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
url: "https://owenbardeen.github.io/flash-tscc-tutorial"

# Sidebar navigation
just_the_docs:
  collections:
    tutorials:
      name: Tutorials
      nav_order: 1


nav:
  - Home: tutorials/index.md
  - Installing Dependencies: tutorials/installing-dependencies.md
  - Compiling FLASH: tutorials/compiling-flash.md
  - Running Interactive Jobs: tutorials/running-interactive.md
  - Batch Jobs: tutorials/batch-jobs.md
  - Troubleshooting: tutorials/troubleshooting.md
